name: lint-test-cover-docs
on:
  push:
    branches:
      - '**'
  workflow_call: # If invoked by build-publish-sign-release workflow.
jobs:
  lint_test_cover_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.6.0"
          python-version: ${{ matrix.python-version }}

      - name: Ensure code is formatted.
        run: |
          uv sync --extra lint
          uv run ruff format --check

      - name: Lint and test module.
        run: |
          uv sync --extra test --extra lint
          uv run pylint nuc # Check against linting rules.
          uv run pyright # Run type checks.
          uv run pytest # Run tests.

      - name: Publish coverage results.
        run: |
          uv sync --extra coveralls
          uv run coveralls --service=github # Submit to coveralls.
        if: matrix.python-version == '3.12'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Test auto-generation of documentation.
        run: |
          uv sync --extra docs
          cd docs && uv run sphinx-apidoc -f -E --templatedir=_templates -o _source ../src && uv run make html && cd ..
